about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('us/', views.AboutUsView.as_view(), name='us'),
]

api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    path('ingredients/', views.get_ingredient),
    path('favorites/', views.add_favorite),
    path('favorites/<int:recipe_id>/', views.delete_favorite),
    path('subscriptions/', views.add_subscription),
    path('subscriptions/<int:user_id>/', views.delete_subscription),
    path('purchases/', views.add_purchase),
    path('purchases/<int:recipe_id>/', views.delete_purchase),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'users.views.page_not_found'
handler500 = 'users.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes.views import (
    edit_recipe, get_recipe, delete_recipe, get_follows, get_author,
    get_shopping_list, delete_shopping_list, get_txt, new_recipe,
    RecipeListView, FavoriteListView
)


urlpatterns = [
    path('', RecipeListView.as_view(), name='index'),
    path('new/', new_recipe, name='new'),
    path('edit/<int:recipe_id>/', edit_recipe, name='edit'),
    path('recipes/<int:recipe_id>/', get_recipe, name='recipe'),
    path('delete/<int:recipe_id>/', delete_recipe, name='delete'),
    path('favorite/', FavoriteListView.as_view(), name='favorite'),
    path('follow/', get_follows, name='follow'),
    path('author/<int:user_id>/', get_author, name='author'),
    path('shopping/', get_shopping_list, name='shopping'),
    path(
        'shopping/<int:recipe_id>/',
        delete_shopping_list,
        name='delete_shopping'
    ),
    path('print/', get_txt, name='print'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор рецепта',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to='recipes/',
        blank=True,
        null=True,
    )
    title = models.TextField(
        verbose_name='Название рецепта',
        max_length=200,
        help_text='Соблюдайте правила орфографии и пунктуации'
    )
    description = models.TextField(
        verbose_name='Описание рецепта',
        max_length=2000,
        help_text='Соблюдайте правила орфографии и пунктуации'
    )
    time = models.PositiveIntegerField(
        verbose_name='Время приготовления',
    )
    is_lunch = models.BooleanField(default=False)
    is_breakfast = models.BooleanField(default=False)
    is_dinner = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['-pk']


class Ingredient(models.Model):
    title = models.TextField(
        verbose_name='Название ингредиента',
        max_length=200
    )
    dimension = models.TextField(
        verbose_name='Единица измерения ингредиента',
        max_length=200
    )

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        unique_together = ('title', 'dimension')


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        null=True,
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        Ingredient,
        null=True,
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        verbose_name='Ингредиент'
    )
    count = models.PositiveIntegerField(
        verbose_name='Количество',
    )

    class Meta:
        verbose_name = 'Ингредиент рецепта'
        verbose_name_plural = 'Ингредиенты рецептов'


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='favorites',
        verbose_name='Пользователь'
    )
    recipe = models.ForeignKey(
        Recipe,
        null=True,
        on_delete=models.CASCADE,
        related_name='favorites',
        verbose_name='Рецепт'
    )

    class Meta:
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='shopping_lists',
        verbose_name='Пользователь'
    )
    recipe = models.ForeignKey(
        Recipe,
        null=True,
        on_delete=models.CASCADE,
        related_name='shopping_lists',
        verbose_name='Рецепт'
    )

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

recipes/forms.py
from django import forms

from recipes.models import Recipe, RecipeIngredient


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['count']


class RecipeForm(forms.Form):
    class Meta:
        model = Recipe

    title = forms.CharField()
    description = forms.CharField()
    time = forms.IntegerField()

recipes/views.py
import mimetypes
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView

from recipes.forms import RecipeForm
from recipes.models import Recipe, Favorite, ShoppingList
from recipes.utils import (
    get_data_tags, shopping_counter, make_shopping_list,
    get_favorite_recipes_id, check_tags, make_ingredients, save_recipe,
    update_recipe, update_ingredients
)
from users.models import Subscription

User = get_user_model()

RECIPE_ON_PAGE = 6


def delete_recipe(request, recipe_id):
    """Удаление рецепта автором."""
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.user != recipe.author:
        return redirect('index')
    recipe.delete()
    return redirect('index')


class RecipeListView(ListView):
    """Просмотр всех рецептов."""
    model = Recipe
    template_name = 'index.html'
    paginate_by = 6
    context_object_name = 'recipes'

    def get_queryset(self):
        recipes, _, _ = check_tags(
            Recipe.objects.all(),
            self.request.GET.get('tag')
        )
        return recipes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['favorites'] = get_favorite_recipes_id(self.request)
        context['shopping_recipes'] = shopping_counter(self.request.user)
        context['index'] = True
        _, context['tag'], context['tags'] = check_tags(
            Recipe.objects.all(),
            self.request.GET.get('tag')
        )
        return context


class FavoriteListView(LoginRequiredMixin, ListView):
    """Просмотр избранных рецептов."""
    model = Recipe
    template_name = 'favorite.html'
    paginate_by = 6
    context_object_name = 'recipes'


    def filter_recipes(self):
        favorites = self.request.user.favorites.all()
        recipes = []
        for el in favorites:
            if el.recipe:
                recipes.append(el.recipe.pk)
        return recipes

    def get_queryset(self):
        recipes, _, _ = check_tags(
            Recipe.objects.filter(pk__in=self.filter_recipes()),
            self.request.GET.get('tag')
        )
        return recipes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['favorites'] = get_favorite_recipes_id(self.request)
        context['shopping_recipes'] = shopping_counter(self.request.user)
        context['favorite'] = True
        _, context['tag'], context['tags'] = check_tags(
            Recipe.objects.filter(pk__in=self.filter_recipes()),
            self.request.GET.get('tag')
        )
        return context


def get_author(request, user_id):
    """Просмотр рецептов автора."""
    author = get_object_or_404(User, pk=user_id)
    recipes, tag, tags = check_tags(
        author.recipes.all(),
        request.GET.get('tag')
    )
    favorite_recipes_id = get_favorite_recipes_id(request)
    shopping_recipes = shopping_counter(request.user)
    follow = False
    if request.user.is_authenticated:
        is_follower = request.user.subscriptions.filter(author=author)
        if is_follower:
            follow = True
    paginator = Paginator(recipes, RECIPE_ON_PAGE)
    page_number = request.GET.get('page')
    recipes = paginator.get_page(page_number)
    return render(
        request,
        'author.html',
        {
            'recipes': recipes,
            'favorites': favorite_recipes_id,
            'author': author,
            'follow': follow,
            'paginator': paginator,
            'shopping_recipes': shopping_recipes,
            'tag': tag,
            'tags': tags,
        }
    )


def get_recipe(request, recipe_id):
    """Просмотр рецепта."""
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    ingredients = recipe.recipe_ingredients.all()
    favorite = []
    follow = False
    shopping_recipes = shopping_counter(request.user)
    if request.user.is_authenticated:
        favorite = Favorite.objects.filter(user=request.user, recipe=recipe)
        is_follower = Subscription.objects.filter(
            user=request.user,
            author=recipe.author
        )
        if is_follower:
            follow = True
    return render(
        request,
        'recipe.html',
        {
            'recipe': recipe,
            'ingredients': ingredients,
            'favorite': favorite,
            'follow': follow,
            'shopping_recipes': shopping_recipes,
        }
    )


def get_follows(request):
    """Просмотр страницы подписок на авторов."""
    if not request.user.is_authenticated:
        return redirect('index')
    follows = request.user.subscriptions.all()
    data = []
    for follow in follows:
        recipes = follow.author.recipes.all()
        temp_data = {
            'author': follow.author,
            'recipes': recipes[:3],
            'count': len(recipes) - 3
        }
        data.append(temp_data)
    paginator = Paginator(data, RECIPE_ON_PAGE)
    page_number = request.GET.get('page')
    data = paginator.get_page(page_number)
    return render(
        request,
        'follow.html',
        {
            'follows': follows,
            'subscription': True,
            'data': data,
            'paginator': paginator
        }
    )


def get_shopping_list(request):
    """Просмотр листа покупок."""
    if not request.user.is_authenticated:
        return redirect('index')
    return render(
        request,
        'shopping.html',
        {
            'shopping': True
        }
    )


def delete_shopping_list(request, recipe_id):
    """Удаление рецепта из листа покупок."""
    if not request.user.is_authenticated:
        return redirect('index')
    shopping_list = ShoppingList.objects.filter(
        user=request.user,
        recipe__id=recipe_id
    )
    for el in shopping_list:
        el.delete()
    return redirect('shopping')


def get_txt(request):
    """Загрузка .txt файла со списком покупок."""
    if not request.user.is_authenticated:
        return redirect('index')
    data = make_shopping_list(request)
    date = datetime.now().date()
    f = open('shopping_list.txt', 'w', encoding='utf-8')
    f.write(
        '\n'
        f'Список покупок {request.user.username}. Дата {date}.\n\n'
        '\n'
    )
    i = 1
    for item in data:
        if i < 10:
            j = ' '
        else:
            j = ''
        f.write(
            f'{j}{i}. [ ]  {item} {data.get(item)[0]} {data.get(item)[1]}.\n\n'
        )
        i += 1

    f.close()
    fl_path = 'shopping_list.txt'
    filename = f'shopping_list_{request.user.username}_{date}.txt'

    fl = open(fl_path, 'r')
    mime_type, _ = mimetypes.guess_type(fl_path)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response


def new_recipe(request):
    """Создание нового рецепта."""
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        errors, fields, ingredients = make_ingredients(request)
        data, tags = get_data_tags(request)
        for key in data:
            fields[key] = data[key]
        form = RecipeForm(data=data)
        image = request.FILES.get('file')
        if not image or 'image' not in image.content_type:
            errors['image'] = True
        else:
            errors['image'] = False
        if form.is_valid() and not errors['image'] and ingredients:
            pk = save_recipe(form.cleaned_data, request, ingredients, tags)
            return redirect('recipe', pk)
        for error in form.errors:
            errors[error] = True
        return render(
            request,
            'new.html',
            {
                'errors': errors,
                'new': True,
                'fields': fields
            }
        )
    return render(
        request,
        'new.html',
        {
            'new': True,
        }
    )


def edit_recipe(request, recipe_id):
    """Редактирование рецепта."""
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.user != recipe.author:
        return redirect('index')
    if request.method == 'POST':
        errors, old_recipe_ingredients = update_ingredients(recipe, request)
        data, tags = get_data_tags(request)
        form = RecipeForm(data=data)
        image = request.FILES.get('file')
        if image and 'image' not in image.content_type:
            errors['image'] = True
        else:
            errors['image'] = False
        if form.is_valid() and old_recipe_ingredients and not errors['image']:
            update_recipe(recipe, form.cleaned_data, tags, request, image)
            return redirect('recipe', recipe.pk)
        for error in form.errors:
            errors[error] = True
        ingredients = recipe.recipe_ingredients.all()
        return render(
            request,
            'edit.html',
            {
                'recipe': recipe,
                'ingredients': ingredients,
                'errors': errors,
            }
        )
    ingredients = recipe.recipe_ingredients.all()
    return render(
        request,
        'edit.html',
        {
            'recipe': recipe,
            'ingredients': ingredients,
        }
    )

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %} </title>
    {% load static %}
    {% block css %}
    {% endblock css %}
</head>
    <body class="body">
        {% include 'nav.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'footer.html' %}

        {% block scripts %}

        {% endblock scripts %}
    </body>

</html>

templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Редактирование рецепта{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock css %}


{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Редактирование рецепта</h1>
        </div>
        <div class="form-container">
            <form action="{% url 'edit' recipe.pk %}" class="form" method="post" enctype="multipart/form-data">

                {% csrf_token %}

                <div class="form__group">
                    <label for="id_name" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        <input type="text" id="id_name" name="name" class="form__input" value="{{ recipe.title }}">
                        <span class="form__error">{% if errors.title %} Добавьте название {% endif %}</span>
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">
                            <div class="tags__item">
                                <input type="checkbox" name="breakfast" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange" {% if recipe.is_breakfast %} checked {% endif %}>
                                <label for="id_breakfast" class="tags__label">Завтрак</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="lunch" id="id_lunch" class="tags__checkbox tags__checkbox_style_green" {% if recipe.is_lunch %} checked {% endif %}>
                                <label for="id_lunch" class="tags__label">Обед</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" {% if recipe.is_dinner %} checked {% endif %}>
                                <label for="id_dinner" class="tags__label">Ужин</label>
                            </div>
                        </div>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">

                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>
                        <div class="form__field-group-ingredientes-container">

                            {% for el in ingredients %}
                            <div class="form__field-item-ingredient" id="ing_{{ el.pk }}">
                                <span> {{ el.ingredient.title.capitalize }} {{ el.count }} {{ el.ingredient.dimension }}.</span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_{{ el.pk }}" name="nameIngredient_{{ el.pk }}" type="hidden" value="{{ el.ingredient.title }}">
                                <input id="valueIngredient_{{ el.pk }}" name="valueIngredient_{{ el.pk }}" type="hidden" value="{{ el.count }}">
                                <input id="unitsIngredient_{{ el.pk }}" name="unitsIngredient_{{ el.pk }}" type="hidden" value="{{ el.ingredient.dimension }}">
                            </div>
                            {% endfor %}

                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">{% if errors.ingredient %} Добавьте ингредиент {% endif %}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_time" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        <input type="number" id="id_time" name="name" class="form__input" min="0" value="{{ recipe.time }}">
                        <label for="id_time" class="form__label">минут</label>
                        <span class="form__error">{% if errors.time %} Добавьте время {% endif %}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description" class="form__label">Описание</label>
                    <div class="form__field-group">
                        <textarea name="description" id="id_description" rows="8" class="form__textarea" >{{ recipe.description }}</textarea>
                        <span class="form__error">{% if errors.description %} Добавьте описание {% endif %}</span>
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        <label for="id_file" class="form__file-button">Выбрать файл</label>
                        <input type="file" class="form__file" name="file" id="id_file" value="{{ recipe.image.url }}">
                        <span class="form__error">{% if errors.image %} Добавьте картинку {% endif %}</span>
                    </div>
                </div>
                <div class="form__footer">
                    <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="{% url 'delete' recipe.pk %}" class="form__ingredient-link">Удалить</a>
                </div>
            </form>
        </div>
    </main>
{% endblock content%}


{% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock scripts%}

templates/footer.html
<footer class="footer">
        <div class="footer__container container">
            <a href="{% url 'about:us' %}" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
</footer>

    

templates/new.html
{% extends "base.html" %}
{% load static %}
{% block title %}Создание рецепта{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock css %}


{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Создание рецепта</h1>
        </div>
        <div class="form-container">

           {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error.errors.as_text }}
            </div>
            {% endfor %}

            {% if form.non_field_errors %}
                <span class="form__error">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}

            <form action="{% url 'new' %}" class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="id_name" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        <input type="text" id="id_name" name="name" class="form__input" value="{{ fields.title }}">
                        <span class="form__error">{% if errors.title %} Добавьте название {% endif %}</span>
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">
                            <div class="tags__item">
                                <input type="checkbox" name="breakfast" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                                <label for="id_breakfast" class="tags__label">Завтрак</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="lunch" id="id_lunch" class="tags__checkbox tags__checkbox_style_green" checked>
                                <label for="id_lunch" class="tags__label">Обед</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" checked>
                                <label for="id_dinner" class="tags__label">Ужин</label>
                            </div>
                        </div>
                        <span class="form__error"></span>
                    </div>
                </div>
                    <div class="form__group">
                        <label for="nameIngredient" class="form__label">Ингредиенты</label>
                        <div class="form__field-group">
                            <div class="form__field-group-ingredientes">
                                <div class="form__dropdown">
                                    <input type="text" id="nameIngredient" class="form__input">
                                    <div class="form__dropdown-items"></div>
                                </div>
                                <input type="number" id="cantidad" class="form__input" min="0">
                                <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                            </div>
                            <div class="form__field-group-ingredientes-container">

                                {% for el in fields.ingredients %}
                                <div class="form__field-item-ingredient" id="ing_{{ el.pk }}">
                                    <span> {{ el.name }} {{ el.value }} {{ el.units }}.</span>
                                    <span class="form__field-item-delete"></span>
                                    <input id="nameIngredient_{{ el.pk }}" name="nameIngredient_{{ el.pk }}" type="hidden" value="{{ el.name }}">
                                    <input id="valueIngredient_{{ el.pk }}" name="valueIngredient_{{ el.pk }}" type="hidden" value="{{ el.value }}">
                                    <input id="unitsIngredient_{{ el.pk }}" name="unitsIngredient_{{ el.pk }}" type="hidden" value="{{ el.units}}">
                                </div>
                                {% endfor %}
                            </div>
                            <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                            <span class="form__error">{% if errors.ingredient %} Добавьте ингредиент {% endif %}</span>
                        </div>
                    </div>
                    <div class="form__group">
                        <label for="id_time" class="form__label">Время приготовления</label>
                        <div class="form__field-group form__field-group_time">
                            <input type="number" id="id_time" name="name" class="form__input" min="0" value="{{ fields.time }}">
                            <label for="id_time" class="form__label">минут</label>
                            <span class="form__error">{% if errors.time %} Добавьте время {% endif %}</span>
                        </div>
                    </div>
                    <div class="form__group">
                        <label for="id_description" class="form__label">Описание</label>
                        <div class="form__field-group">
                            <textarea name="description" id="id_description" rows="8" class="form__textarea">{{ fields.description }}</textarea>
                            <span class="form__error">{% if errors.description %} Добавьте описание {% endif %}</span>
                        </div>
                    </div>
                    <div class="form__group">
                        <span class="form__label">Загрузить фото</span>
                        <div class="form__field-group">
                            <label for="id_file" class="form__file-button">Выбрать файл</label>
                            <input type="file" class="form__file" name="file" id="id_file">
                            <span class="form__error">{% if errors.image %} Добавьте картинку {% endif %}</span>
                        </div>
                    </div>
                    <div class="form__footer">
                        <button class="button button_style_blue">Создать рецепт</button>
                    </div>
            </form>
        </div>

    </main>
{% endblock content%}


{% block scripts %}

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>

{% endblock scripts%}

templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
        <ul class="pagination__container">
            {% if items.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}{% if tag %}&tag={{ tag }}{% endif %}"><span class="icon-left"></span></a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" ><span class="icon-left"></span></a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if items.number == i %}
                    <li class="pagination__item pagination__item_active"><a class="pagination__link link" >{{ i }}</a></li>
                {% else %}
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}{% if tag %}&tag={{ tag }}{% endif %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if items.has_next %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}{% if tag %}&tag={{ tag }}{% endif %}"><span class="icon-right"></span></a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" ><span class="icon-right"></span></a></li>
            {% endif %}
        </ul>
</nav>